In [1]:
import numpy as np

# NumPy Assignment 

## Suppose you have a superstore which runs 24/7. Your tasks are to:

1) Create a dataset of the sale transactions of each day and each hour for the Month of January. Each row contains in the array should contain 23 records. Each index will represent total sale in that hour. e.g row 0 will contain the array of 23 transactions of Jan 1st. Now the 0 index of each row should contain the total sale made at 00:00 hours of respective date

In [35]:
data = np.random.randint(low =1, high = 100, size= (31,24))

In [36]:
data

array([[55, 55, 70, 67, 65, 44, 16, 25, 80, 35, 89, 46, 61, 35, 22,  4,
        84, 84, 95, 55, 29,  1, 35, 63],
       [12, 68, 63, 42, 75, 71, 98, 62, 44, 52,  8, 57, 95,  9, 32, 32,
        50, 79, 59, 74,  1, 34,  4, 79],
       [23, 63, 29, 44, 45, 55, 89, 40, 40,  4,  9, 19, 45, 34, 95, 42,
        26, 38, 64, 78, 56, 36, 23, 92],
       [22, 70, 51, 54, 62, 22, 12, 47, 18, 64, 51, 78, 73, 23, 87, 36,
        64, 92, 78, 42, 27, 37, 71, 70],
       [49, 23,  5, 62, 25, 91,  1, 76, 42, 45, 10, 19, 97, 95, 12, 60,
        60, 82, 81, 53, 80, 72, 84, 48],
       [61, 27, 22, 31, 97, 89, 15, 95, 34, 20, 21, 44, 84, 78, 27, 71,
        69, 88, 38, 13, 27, 49,  2, 49],
       [90, 96, 64, 69, 97, 56, 80, 79, 36, 85, 25, 25, 14, 56, 73, 35,
        99, 18, 72, 17, 58, 98,  5, 77],
       [58, 30,  1, 31, 72, 96, 45, 97, 38, 88, 25,  5, 26, 26, 60, 44,
        66, 15, 30, 18, 61, 48, 92, 54],
       [29, 99, 15, 74,  8, 79, 20, 59, 55, 52, 98, 51, 22, 81, 88, 18,
        97, 49, 77, 85, 

In [38]:
np.size(data,axis=0) #row

31

In [39]:
np.size(data,axis=1) #column

24


2) Calculate Daily Average Sale of this dataset

In [41]:
np.mean(data, axis = 1)

array([50.625     , 50.        , 45.375     , 52.125     , 53.        ,
       47.95833333, 59.33333333, 46.91666667, 59.45833333, 49.33333333,
       46.75      , 55.91666667, 51.79166667, 50.25      , 48.33333333,
       42.58333333, 44.41666667, 46.95833333, 43.375     , 51.20833333,
       48.        , 53.625     , 56.45833333, 57.20833333, 53.41666667,
       39.16666667, 48.79166667, 50.45833333, 46.625     , 52.79166667,
       50.04166667])


3) Calculate the Average Sale of each hour, so that you have insight of the busiest hour in the month.

In [42]:
data.mean(axis=0)

array([45.48387097, 50.25806452, 48.12903226, 53.87096774, 51.77419355,
       44.80645161, 56.67741935, 52.48387097, 51.16129032, 46.58064516,
       53.74193548, 43.4516129 , 48.96774194, 48.77419355, 47.64516129,
       52.51612903, 53.38709677, 46.90322581, 53.70967742, 50.74193548,
       49.5483871 , 50.12903226, 48.38709677, 52.64516129])

4) Calculate the minimum and Maximum Sale of each day.

In [46]:
data.min(axis = 1)

array([ 1,  1,  4, 12,  1,  2,  5,  1,  8,  6,  2,  4,  4,  1,  2,  3,  4,
        2,  2,  4,  3,  2,  4,  4, 11,  1,  1,  1,  9,  6,  2])

In [47]:
np.max(data, axis = 1)

array([95, 98, 95, 92, 97, 97, 99, 97, 99, 98, 94, 95, 98, 99, 95, 96, 99,
       94, 99, 95, 84, 90, 99, 96, 99, 98, 95, 99, 98, 98, 96])

5) Calculate the Minimum and Maximum Sale of each hour.

In [48]:
data.min(axis = 0)

array([4, 2, 1, 1, 7, 3, 1, 6, 4, 2, 2, 1, 1, 1, 4, 3, 3, 2, 5, 3, 1, 1,
       2, 4])

In [49]:
data.max(axis = 0)

array([99, 99, 97, 95, 99, 96, 99, 97, 95, 99, 99, 98, 99, 99, 95, 94, 99,
       92, 95, 94, 88, 98, 92, 98])


6) Calculate Daily Cumulative Sum

In [50]:
data.cumsum(axis=1)

array([[  55,  110,  180,  247,  312,  356,  372,  397,  477,  512,  601,
         647,  708,  743,  765,  769,  853,  937, 1032, 1087, 1116, 1117,
        1152, 1215],
       [  12,   80,  143,  185,  260,  331,  429,  491,  535,  587,  595,
         652,  747,  756,  788,  820,  870,  949, 1008, 1082, 1083, 1117,
        1121, 1200],
       [  23,   86,  115,  159,  204,  259,  348,  388,  428,  432,  441,
         460,  505,  539,  634,  676,  702,  740,  804,  882,  938,  974,
         997, 1089],
       [  22,   92,  143,  197,  259,  281,  293,  340,  358,  422,  473,
         551,  624,  647,  734,  770,  834,  926, 1004, 1046, 1073, 1110,
        1181, 1251],
       [  49,   72,   77,  139,  164,  255,  256,  332,  374,  419,  429,
         448,  545,  640,  652,  712,  772,  854,  935,  988, 1068, 1140,
        1224, 1272],
       [  61,   88,  110,  141,  238,  327,  342,  437,  471,  491,  512,
         556,  640,  718,  745,  816,  885,  973, 1011, 1024, 1051, 1100,
       


7) Calculate Daily Total Sum

In [51]:
data.sum(axis = 1)

array([1215, 1200, 1089, 1251, 1272, 1151, 1424, 1126, 1427, 1184, 1122,
       1342, 1243, 1206, 1160, 1022, 1066, 1127, 1041, 1229, 1152, 1287,
       1355, 1373, 1282,  940, 1171, 1211, 1119, 1267, 1201])

8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset

In [52]:
data>50

array([[ True,  True,  True,  True,  True, False, False, False,  True,
        False,  True, False,  True, False, False, False,  True,  True,
         True,  True, False, False, False,  True],
       [False,  True,  True, False,  True,  True,  True,  True, False,
         True, False,  True,  True, False, False, False, False,  True,
         True,  True, False, False, False,  True],
       [False,  True, False, False, False,  True,  True, False, False,
        False, False, False, False, False,  True, False, False, False,
         True,  True,  True, False, False,  True],
       [False,  True,  True,  True,  True, False, False, False, False,
         True,  True,  True,  True, False,  True, False,  True,  True,
         True, False, False, False,  True,  True],
       [False, False, False,  True, False,  True, False,  True, False,
        False, False, False,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True, False],
       [ True, False, False, False,

8) Use Boolean Indexing to search for records where sale is greater than a defined value, choose an appropriate value depending upon your dataset

In [62]:
condition = data>80
(data[data>80])

array([89, 84, 84, 95, 98, 95, 89, 95, 92, 87, 92, 91, 97, 95, 82, 81, 84,
       97, 89, 95, 84, 88, 90, 96, 97, 85, 99, 98, 96, 97, 88, 92, 99, 98,
       81, 88, 97, 85, 84, 83, 98, 86, 95, 94, 93, 92, 91, 94, 95, 86, 97,
       82, 85, 85, 98, 95, 84, 97, 99, 84, 85, 84, 90, 95, 83, 83, 85, 94,
       95, 87, 96, 99, 88, 86, 94, 99, 84, 86, 95, 82, 86, 81, 83, 84, 90,
       81, 85, 90, 84, 83, 85, 99, 92, 90, 83, 88, 82, 82, 96, 94, 85, 89,
       99, 99, 90, 93, 92, 88, 93, 85, 98, 84, 95, 93, 82, 94, 86, 88, 91,
       90, 99, 86, 93, 98, 87, 81, 95, 86, 98, 94, 86, 95, 82, 87, 96])

In [57]:
data[condition]

array([89, 84, 84, 95, 98, 95, 89, 95, 92, 87, 92, 91, 97, 95, 82, 81, 84,
       97, 89, 95, 84, 88, 90, 96, 97, 85, 99, 98, 96, 97, 88, 92, 99, 98,
       81, 88, 97, 85, 84, 83, 98, 86, 95, 94, 93, 92, 91, 94, 95, 86, 97,
       82, 85, 85, 98, 95, 84, 97, 99, 84, 85, 84, 90, 95, 83, 83, 85, 94,
       95, 87, 96, 99, 88, 86, 94, 99, 84, 86, 95, 82, 86, 81, 83, 84, 90,
       81, 85, 90, 84, 83, 85, 99, 92, 90, 83, 88, 82, 82, 96, 94, 85, 89,
       99, 99, 90, 93, 92, 88, 93, 85, 98, 84, 95, 93, 82, 94, 86, 88, 91,
       90, 99, 86, 93, 98, 87, 81, 95, 86, 98, 94, 86, 95, 82, 87, 96])

In [74]:
#tell how many hours in january giving sale greater than 80 rupees
total_hours = len(data.reshape(31*24))
total_hours

744

In [77]:
hours80 = len(data[data>80])
hours80

135

In [86]:
print(hours80, 'out of', total_hours, 'hours have sale greater than 80 Rupees')

135 out of 744 hours have sale greater than 80 Rupees


In [88]:
day_sale = data.sum(axis= 1)
day_sale

array([1215, 1200, 1089, 1251, 1272, 1151, 1424, 1126, 1427, 1184, 1122,
       1342, 1243, 1206, 1160, 1022, 1066, 1127, 1041, 1229, 1152, 1287,
       1355, 1373, 1282,  940, 1171, 1211, 1119, 1267, 1201])

In [89]:
day_sale>1000

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True])

In [94]:
days_sale1000 = len(day_sale[day_sale> 1000])
print('There are',days_sale1000,'days in which sale is greater than 1000.')

There are 30 days in which sale is greater than 1000.
