In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a*5

array([ 5, 10, 15])

In [5]:
numpyArray = np.array([22,33,44,55])
numpyArray

array([22, 33, 44, 55])

In [8]:
numpyArray = np.array([22,33,44,55], dtype='float32')
print(type(numpyArray))
(numpyArray)

<class 'numpy.ndarray'>


array([22., 33., 44., 55.], dtype=float32)

In [9]:
numpyArray = np.array([22,33,44,55], dtype=np.int8)
print(type(numpyArray))
(numpyArray)

<class 'numpy.ndarray'>


array([22, 33, 44, 55], dtype=int8)

In [10]:
randomArray = np.random.randint(10)

In [11]:
randomArray

4

In [13]:
randomArray = np.random.randn(10)*100
randomArray

array([-150.1644211 ,   88.42488273,  -70.13616608,  147.44764031,
        -91.0702927 ,  -69.59331897, -162.40084226,  -91.30410711,
       -190.22796   , -107.34426814])

In [14]:
randomArray.ndim

1

In [15]:
randomArray.shape

(10,)

In [ ]:
array>>>vector
matrix>>>tensor

In [16]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[3,4,5]])
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 5]])

In [17]:
twoD.shape

(4, 3)

In [18]:
zeroD = np.array(100)
zeroD.ndim

0

In [19]:
zeroD.shape

()

In [21]:
miscD = np.array([99])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[99]
1
(1,)


In [25]:
miscD = np.array([[[99]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [29]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
flat = np.ravel(a)
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
z= np.array([22,33,44,55])
z

array([22, 33, 44, 55])

In [33]:
rz= z.reshape(2,2)
rz

array([[22, 33],
       [44, 55]])

In [35]:
fz = np.ravel(rz)
fz

array([22, 33, 44, 55])

In [40]:
twoD = np.arange(36). reshape(6,6)
twoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
threeD = twoD.reshape(3,3,4)
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [43]:
rebacktwoD = threeD.reshape(6,6)
rebacktwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [45]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,4,5],[5,6,7],[4,5,6]]])
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 4, 5],
        [5, 6, 7],
        [4, 5, 6]]])

In [47]:
twoD + twoD

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

In [48]:
twoD / twoD

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [49]:
twoD * twoD

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])