# Boolean Indexing


In [2]:
import numpy as np

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
data = np.random.randn(7, 4)
data

array([[ 0.61639336,  0.56266961, -0.95953774,  0.18413224],
       [ 1.56657185,  1.06296708,  0.29080655, -2.09101358],
       [ 0.15801829,  1.57546227, -0.68376026,  0.06943692],
       [ 0.07495901,  0.86777088,  2.48761921, -1.22190467],
       [ 0.37825982,  0.1957992 ,  1.40519201,  0.37955758],
       [-0.48179048, -0.15045163, -0.27254893, -0.66866771],
       [-1.6357506 ,  1.22934331, -0.65802493,  0.49339946]])

In [8]:
names == 'Saad'

array([False, False, False, False, False, False, False])

In [9]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [10]:
data >1

array([[False, False, False, False],
       [ True,  True, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [11]:
data[data>1]

array([1.56657185, 1.06296708, 1.57546227, 2.48761921, 1.40519201,
       1.22934331])

In [13]:
bol = np.array([True,False,False,False,False,True, False], dtype= 'bool')
data[bol]
#data[True,False,False,False,False,True, False] #true roww show, false ones dont

array([[ 0.61639336,  0.56266961, -0.95953774,  0.18413224],
       [-0.48179048, -0.15045163, -0.27254893, -0.66866771]])

In [18]:
condition = names!='Bob'

In [20]:
data[~condition]

array([[ 0.61639336,  0.56266961, -0.95953774,  0.18413224],
       [ 0.07495901,  0.86777088,  2.48761921, -1.22190467]])

In [22]:
data[condition,1:3]

array([[ 1.06296708,  0.29080655],
       [ 1.57546227, -0.68376026],
       [ 0.1957992 ,  1.40519201],
       [-0.15045163, -0.27254893],
       [ 1.22934331, -0.65802493]])

In [26]:
data = np.arange(28).reshape(7,4)
print(data)
print(~condition)
data[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[ True False False  True False False False]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [30]:
cond = (names =='Bob') & (names == 'Joe')
cond

array([False, False, False, False, False, False, False])

In [33]:
cond = (names =='Bob') | (names == 'Joe')
cond

array([ True,  True, False,  True, False,  True,  True])

# Fancy Indexing

In [34]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

In [35]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [40]:
arr[[4,0,1,2],[2,3,0,1]] #4 row 2 col, 0 row 3 col,(1,0), (2,1) etc values picked

array([4., 0., 1., 2.])

In [44]:
arr = np.arange(32).reshape(8,4)
print(arr)
arr[[1,5,7,2]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2], 7[0,3,1,2], 2[0,3,1,2]
##(1,0)(1,3)(1,1)(1,2)()()()()()()()()....etc
#1st R,0 C

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [45]:
arr.T #Property Tranpose

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [46]:
arr.transpose() #Function Tranpose

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [67]:
arr1= np.array([1,2,3,5,5,6,6,3])
arr2= np.array([1,2,3,5,5,6,6,3])
arr1
arr2

array([1, 2, 3, 5, 5, 6, 6, 3])

In [68]:
np.unique(arr1) #set

array([1, 2, 3, 5, 6])

In [69]:
np.stack([arr1,arr2])

array([[1, 2, 3, 5, 5, 6, 6, 3],
       [1, 2, 3, 5, 5, 6, 6, 3]])

In [3]:
arr1= np.array([[1,2,3,5],
                [5,6,6,3]])
arr2= np.array([[1,2,3,5],
                [5,6,6,3]])
print(arr1)
print(arr2)

[[1 2 3 5]
 [5 6 6 3]]
[[1 2 3 5]
 [5 6 6 3]]


In [4]:
np.vstack([arr1,arr2])

array([[1, 2, 3, 5],
       [5, 6, 6, 3],
       [1, 2, 3, 5],
       [5, 6, 6, 3]])

In [7]:
np.hstack([arr1,arr2])

array([[1, 2, 3, 5, 1, 2, 3, 5],
       [5, 6, 6, 3, 5, 6, 6, 3]])

In [8]:
np.stack([arr1,arr2])

array([[[1, 2, 3, 5],
        [5, 6, 6, 3]],

       [[1, 2, 3, 5],
        [5, 6, 6, 3]]])

In [3]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
np.hsplit(arr,1)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [2]:
import numpy as np

In [43]:
x= np.array([[1,2,4]])
print(x.shape)
print(x)

y= np.array([[4],[5],[2]])
print(y.shape)
print(y)

(1, 3)
[[1 2 4]]
(3, 1)
[[4]
 [5]
 [2]]


In [44]:
x,y=np.broadcast_arrays(x,y)

In [45]:
x

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [46]:
y

array([[4, 4, 4],
       [5, 5, 5],
       [2, 2, 2]])

In [47]:
np.union1d(x,y)

array([1, 2, 4, 5])

In [48]:
np.intersect1d(x,y)

array([2, 4])

In [49]:
np.unique(y)

array([2, 4, 5])

In [50]:
np.in1d(y, x) #Compute a boolean array indicating whether each element of y is contained in x

array([ True,  True,  True, False, False, False,  True,  True,  True])

In [51]:
np.setdiff1d(y, x) #Set difference, elements in y that are not in x

array([5])

In [52]:
np.save('some array',x,y)

In [53]:
np.load('some array.npy')

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

In [54]:
np.dot(x,y)

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

In [55]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])


In [56]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [57]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [58]:
x.dot(y) # there is a function dot, both an array method
#and a function in the numpy namespace, for matrix multiplication:


array([[ 28.,  64.],
       [ 67., 181.]])

In [59]:
np.trace(x) #Compute the sum of the diagonal elements

6.0

In [60]:
np.diag(x)

array([1., 5.])