# Slicing

In [1]:
import numpy as np

In [2]:
arr1D = np.array([44,55,66,77])
arr1D

array([44, 55, 66, 77])

In [3]:
arr1D[3]

77

In [4]:
arr1D[-1]

77

In [6]:
arr1D[1:2]

array([55])

In [7]:
arr1D[1:3]

array([55, 66])

In [9]:
arr2D = np.array([[22,33,44],[55,66,77],[88,99,100]])
arr2D

array([[ 22,  33,  44],
       [ 55,  66,  77],
       [ 88,  99, 100]])

In [10]:
arr2D[1]

array([55, 66, 77])

In [11]:
arr2D[1][2]

77

In [12]:
arr2D[1,2]

77

In [13]:
arr2D[:2]

array([[22, 33, 44],
       [55, 66, 77]])

In [14]:
arr2D[:2,1:]

array([[33, 44],
       [66, 77]])

In [17]:
arr3D = np.array([[[100,200,300],[400,500,600],[700,800,900]]])
arr3D

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [18]:
arr3D.shape

(1, 3, 3)

In [19]:
arr3D.ndim

3

In [21]:
arr3D[0][2]

array([700, 800, 900])

In [32]:
arrD = np.array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],
        [[1,2,3],
      [4,5,6],
       [7,8,9]]])
arrD

array([[[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]],

       [[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]]])

In [1]:
arrD[1][1]

NameError: name 'arrD' is not defined

In [37]:
arrD[0][2]

array([700, 800, 900])

In [38]:
arrD[0,:2,1:]

array([[200, 300],
       [500, 600]])

In [74]:
arr = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
arr

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5],
       [ 4,  0,  6,  2,  5],
       [ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [82]:
arr[2:4,2:5]

array([[6, 2, 5],
       [3, 4, 5]])

In [78]:
arr[4:5,0:6]

array([[4, 5, 6, 7, 8]])

In [76]:
arr[4:5,0:5]

array([[4, 5, 6, 7, 8]])

In [75]:
arr[2]

array([4, 0, 6, 2, 5])

In [81]:
arr[:,3]

array([ 8,  4,  2,  4,  7, 10])

In [83]:
arr[1:5,0:6]

array([[1, 2, 3, 4, 5],
       [4, 0, 6, 2, 5],
       [1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [85]:
arr[2:4,4:6] #giving in 2D

array([[5],
       [5]])

In [89]:
arr[2:4,-1]#giving vector

array([5, 5])

In [92]:
arr[2:4,4]

array([5, 5])

In [93]:
arr[2:4,4:]

array([[5],
       [5]])

In [94]:
arr[:,:2]

array([[2, 4],
       [1, 2],
       [4, 0],
       [1, 2],
       [4, 5],
       [7, 8]])

In [96]:
arr[:,::2] #step one column

array([[ 2,  6, 10],
       [ 1,  3,  5],
       [ 4,  6,  5],
       [ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [98]:
arr[::3,:] #2 step ::3, 1 step ::2

array([[ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5]])