In [1]:
import numpy as np

In [10]:
a= np.arange(5)

In [14]:
a

array([0, 1, 2, 3, 4])

In [17]:
a.dtype


dtype('int32')

In [16]:
a.shape

(5,)

In [24]:
arr = np.array([[5],[4]])

In [25]:
arr

array([[5],
       [4]])

In [49]:
arr = np.ones([4,4],dtype=int)

In [50]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
arr = np.arange(4,6)

In [55]:
arr

array([4, 5])

In [66]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
arr.reshape(2,4)
arr.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [76]:
arr = np.arange(15).reshape(3,-1)

In [77]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[6,5,4],[3,2,1]])

In [80]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
b

array([[6, 5, 4],
       [3, 2, 1]])

In [83]:
c = np.concatenate([a,b])

In [84]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4],
       [3, 2, 1]])

In [124]:
c = np.concatenate([a,b],axis=1)
d=np.vstack((a,b)) #axis 0 mean row wise

In [125]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4],
       [3, 2, 1]])

In [123]:
c

array([[1, 2, 3, 6, 5, 4],
       [4, 5, 6, 3, 2, 1]])

In [98]:
arr = np.random.randn(4,2)

In [99]:
arr

array([[ 1.5339312 , -0.41191466],
       [ 1.09487658,  1.28343034],
       [-0.47185725, -0.4475083 ],
       [-1.3004222 ,  0.49302652]])

In [115]:
f,s,t=np.split(arr, [2,2])

In [116]:
f

array([[ 1.5339312 , -0.41191466],
       [ 1.09487658,  1.28343034]])

In [117]:
s

array([], shape=(0, 2), dtype=float64)

In [118]:
t

array([[-0.47185725, -0.4475083 ],
       [-1.3004222 ,  0.49302652]])

In [140]:
h = np.hsplit(arr, (1,3))

In [141]:
h

[array([[ 1.5339312 ],
        [ 1.09487658],
        [-0.47185725],
        [-1.3004222 ]]), array([[-0.41191466],
        [ 1.28343034],
        [-0.4475083 ],
        [ 0.49302652]]), array([], shape=(4, 0), dtype=float64)]

In [155]:
arr = np.arange(3)
rep = arr.repeat([2,3,4])

In [156]:
rep

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [174]:
arr = np.array([[3,2],[4,2]])
rep = arr.repeat([2,3], axis=1)

In [175]:
arr

array([[3, 2],
       [4, 2]])

In [176]:
rep

array([[3, 3, 2, 2, 2],
       [4, 4, 2, 2, 2]])

In [184]:
t = np.tile(arr,(2,2))

In [185]:
t

array([[3, 2, 3, 2],
       [4, 2, 4, 2],
       [3, 2, 3, 2],
       [4, 2, 4, 2]])

In [197]:
ar = np.zeros([2,3,4])
arr = np.ones([2,3,4], dtype=int)

In [198]:
ar

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [202]:
arr= np.arange(0,99)

In [203]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [204]:
a = [2, 3.2, 5.5, -6.4, -2.2, 2.4] 

In [205]:
a

[2, 3.2, 5.5, -6.4, -2.2, 2.4]

In [207]:
arr = np.reshape(a, [2,3])

In [208]:
arr

array([[ 2. ,  3.2,  5.5],
       [-6.4, -2.2,  2.4]])

In [215]:
arr[0:,:2]

array([[ 2. ,  3.2],
       [-6.4, -2.2]])

In [227]:
arr[0:2,1]

array([ 3.2, -2.2])

In [228]:
a=np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])

In [229]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [250]:
arr = np.array([[1,2,3],[4,5,6],[6,5,4],[3,2,1]])

In [251]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4],
       [3, 2, 1]])

In [266]:
arr.mean(1).reshape(4,1) #column mean (0) row mean (1)

array([[2.],
       [5.],
       [5.],
       [2.]])

In [272]:
demeaned= arr - arr.mean(0)

In [273]:
demeaned

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5],
       [ 2.5,  1.5,  0.5],
       [-0.5, -1.5, -2.5]])

In [269]:
demeaned.mean(1)

array([-1.5,  1.5,  1.5, -1.5])

arr = np.array.range(4)

In [290]:
arr1 = np.arange(4)
arr2 = np.arange(10,14)

In [291]:
arr1

array([0, 1, 2, 3])

In [292]:
arr2

array([10, 11, 12, 13])

In [293]:
arr= np.array([arr1,arr2])

In [294]:
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [295]:
arr.size

8

In [296]:
arr.shape

(2, 4)

In [306]:
arr.max()

13

In [307]:
arr.min()

0

In [308]:
arr.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [309]:
arr.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [310]:
arr.flatten()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [323]:
arr.dtype=float

In [324]:
arr

array([[2.12199579e-314, 6.36598737e-314],
       [2.33419537e-313, 2.75859453e-313]])

In [331]:
arr = np.arange(0,21)

In [332]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [333]:
a = np.diag(np.arange(3))

In [334]:
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [341]:
np.arange(6) #[:, np.newaxis]

array([0, 1, 2, 3, 4, 5])

In [337]:
np.arange(0, 51, 10)

array([ 0, 10, 20, 30, 40, 50])

In [339]:
np.arange(6) + np.arange(0, 51, 10)

array([ 0, 11, 22, 33, 44, 55])

In [342]:
np.arange(6) + np.arange(0, 51, 10) [:, np.newaxis]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [344]:
multiple = np.arange(0,30,3)
multiple

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [359]:
x = np.array([0,1,2,3,4,5],dtype=float)

In [360]:
print(x)

[0. 1. 2. 3. 4. 5.]


In [378]:
a = np.arange(0,0.8,0.1)

In [379]:
a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7])

In [385]:
arr=np.arange(10)

In [386]:
np.add.reduce(arr)

45

In [390]:

np.sum(arr)

45

In [392]:
a=np.random.seed(12346)

In [486]:
arr = np.array([[[5,4,3,2,1],[5,4,6,8,7],[1,2,3,4,5],
                [5,5,5,5,5],[5,4,3,2,1]]])

In [487]:
arr

array([[[5, 4, 3, 2, 1],
        [5, 4, 6, 8, 7],
        [1, 2, 3, 4, 5],
        [5, 5, 5, 5, 5],
        [5, 4, 3, 2, 1]]])

In [488]:
arr[:1,::2,:1]

array([[[5],
        [1],
        [5]]])

In [489]:
arr[::2].sort()

In [490]:
arr

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8],
        [1, 2, 3, 4, 5],
        [5, 5, 5, 5, 5],
        [1, 2, 3, 4, 5]]])

In [491]:
arr[:, :-1] < arr[:, 1:]

array([[[ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [ True,  True,  True,  True, False],
        [False, False, False, False, False]]])

In [492]:
arr.resize(5,5)

In [493]:
arr

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5],
       [5, 5, 5, 5, 5],
       [1, 2, 3, 4, 5]])

In [494]:
arr.flat[[1,3]]=1

In [484]:
arr

array([[1, 1, 1, 1, 1],
       [4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5],
       [5, 5, 5, 5, 5],
       [1, 2, 3, 4, 5]])

In [495]:
arr.tolist()

[[1, 1, 3, 1, 5],
 [4, 5, 6, 7, 8],
 [1, 2, 3, 4, 5],
 [5, 5, 5, 5, 5],
 [1, 2, 3, 4, 5]]

In [499]:
arr=np.arange(15).reshape(3,5)

In [501]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [503]:
np.add.accumulate(arr,axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27]], dtype=int32)